logging:
  level:
    root: info
    mybatis: debug
    sql: debug
    runTimeCount: info

spring:
  application:
    name: growlithe-computer
  profiles:
    active: dev
  datasource:
    mysql:
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 100
      max-idle: 10
      max-wait: 10000
      default-auto-commit: false
      time-between-eviction-runs-millis: 30000
      min-evictable-idle-time-millis: 30000
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      validation-query: SELECT 1

client:
  healthcheck:
  enabled: true

#eureka:
#  instance:
#    lease-renewal-interval-in-seconds: 5
#    lease-expiration-duration-in-seconds: 10
