logging:
  path: ./logs

spring:
  datasource:
    mysql:
     jdbc-url: jdbc:mysql://localhost:3306/practice?useAffectedRows=true&autoReconnect=true&amp;autoReconnectForPools=true&allowMultiQueries=true
     username: growlithe
     password: growlithe

#  redis:
#    host: redis-dev.idc.yst.com.cn
#  http:
#    multipart:
#      max-file-size: 20Mb
#      max-request-size: 100Mb

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://eureka-dev.idc.yst.com.cn:8080/eureka/
#
#dubbo:
#  zookeeper:
#    address: zookeeper-dev.idc.yst.com.cn:2181
#  protocol:
#    port: 20888
#
#attachment:
#  path:  /Users/wangxin/
#
#nfsq:
#  sso:
#    url: http://firefox-mrk.test.yst.com.cn/NFSpring_auth_service/web/desktop/initDesktop